name: CalculatorChecks

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    runs-on: ubuntu-latest

    steps:
      - name: Check-outRepository
        uses: actions/checkout@v2
      
      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Flake8
        run: | 
          pip install flake8
          flake8 . 

      - name: InstallDeps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: StartTests
        run: pytest -vv
          # run: python -m unittest Calculator/tests.py