name: CalculatorChecks

on:
  push:
   branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]

    runs-on: ubuntu-latest
    
    steps:
      - name: Check-out Repository
        uses: actions/checkout@v3
      
      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
          cache: 'pip'

      - name: InstallDeps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Tests
        run: python -m unittest

      - name: Convert to Exe
        run: |
          pip install pyinstaller
          pyinstaller --onefile main.py

      - name: Create a file
        run: echo "I won't live long" > my_file.txt
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: my-artifact
          path: my_file.txt
          retention_days: 1

      - name: Check Directory
        run: | 
          ls -al